#+title: Script of the Slide Guys
#+author: Human

** Aditya
+ So here we are pitching the idea of hooking people upto VR glasses, but who does it really help?
  - It obviously helps students like myself practical skills without needing to access tools  that might otherwise be expensive or unaccessible, giving way to better and effective learning with hands on experience.
  - It also helps educators, from teachers to lecturers, to push the boundaries of teaching and teach without having to worry about visualizing concepts, produce engaging content and change the traditional 'imagine-sutff-in-your-head' style of teaching and putting it right infront of you.
  - And it doesnt end there. Research from MIT AgeLab found that adults who used VR systems were more likely to feel positive about their health and emotions. With that in mind, they can continue learning, and experience the latest trends.

** Harsh
+ EdeVR (Ed Wrr) is a project that explores the idea of immersive learning, it lets children learn practical skills without access to real tools with hands-on exp while allowing teachers to push the boundaries of student engagement.
+ Our exp (waiting list): Our project sailed smoothly with the help of our mentor, Ms. Vickie Culberston and the marvelous powertalks gave us all something to take home with us. This was once in a lifetime experience that allowed us to work with people from different parts of the globe and are glad we got to be a part of it.

** Bianca
+ Benjamin Franklin once said: An investment in knowledge pays the best interest. Hello all, Im Biancaa, my friends and I are going to present on our project EdeVR (Edwar), the next step of education.
  - Lets look at EdeVR help a school student called martha.
  - In EdeVR compatible books, QR codes will be printed in beside difficult concepts, that take the students into a virtual environment where theyre able to immerse themselves in learning.
    - As a part of the prototype:
      1. We wrote a program that generates QR code of a given input.
      2. The decoder then decodes the QR.
      3. And an API request takes the user to the EdStore where they can either download the environment (en wire ment) offline or learn with friends online.

** Anant
+ Now lets go through a brief walkthrough of our project design, when we are required to login via either school or personal account, we are then greeted by relevant news and an Assistant suggesting topics we might like.
  - We then move onto the subject area where we currently plan on supoprting 4 main subjects, Chemistry, Anatomy, Music and Geography.
  - Moving on we enter the main room where we experience the best of VR, a first person view where one can interact with VR Models for the best visual learning experience.
  - Alongside the main interface we have an app which shows us stuff like classnotes and assignments without having to enter the EdeVR all the Time.
+ Now about the future extensions. Being differently abled poses a different challenge in learning, but through EdeVR they never have to worry about being left out of things, without the disconnect of Online classes.
  - We plan on improving the EdStore concept to let users upload their own models, and achieve complete Assistant integration in the EdeVR world.
  - We intend to extend the reach of our software to the world, and that means adding curriculums of different countries.
  - Making the app publically funded would help the app become available everywhere easily.
  - Make it available worldwide also means making the software multilingual.
  - We also thought about the benefits which it may have if we promote further development of EdeVR, it could possibly support higher educations such as medical colleges or mechanical engineering where hands on skills are a must, this method could conserve a lot of resources and is a cost effective solution.
